### ISSUE TITLE
Page action icons should not display on non-content pages

### ISSUE THREAD

**Issue by penguinstyles** [FlexWiki/editorial#1]
Action icons (edit, delete, history, etc.) should not be displayed on pages that are not editable.

**Comment by WikiNetworks** [comment]
Submitted a pull request for this, take a look

**Comment by WikiNetworks** [comment]
Suppose since this is fixed, we can close this issue

**Comment by penguinstyles** [comment]
Fixed by #2

Thanks! 🙏
